# Generated by Django 4.0.1 on 2022-02-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Класс')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('comment', models.TextField(blank=True, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Пол')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Полы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ограничение')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Ограничение',
                'verbose_name_plural': 'Ограничения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(default='Классный руководитель', max_length=255, verbose_name='Должность')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('comment', models.TextField(blank=True, verbose_name='Заметка')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='classroom.classroom')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schoolboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фамилия Имя')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('comment', models.TextField(blank=True, verbose_name='Заметка')),
                ('energy', models.BooleanField(default=False, verbose_name='Активный')),
                ('height', models.CharField(blank=True, max_length=3, verbose_name='Рост, см.')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolboy', to='classroom.classroom')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolboy', to='classroom.gender')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolboy', to='classroom.requirement')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Рассадка')),
                ('create_data', models.DateField(auto_now_add=True, verbose_name='Дата начала рассадки')),
                ('end_data', models.DateField(auto_now_add=True, verbose_name='Дата окончания рассадки')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='classroom.classroom')),
            ],
            options={
                'verbose_name': 'Рассадка',
                'verbose_name_plural': 'Рассадки',
                'ordering': ['position'],
            },
        ),
    ]
