# Generated by Django 4.0.1 on 2022-02-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
    ]
