# Generated by Django 4.0.1 on 2022-03-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_requirement_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='save',
            field=models.BooleanField(default=False, verbose_name='Сохранение в БД'),
        ),
        migrations.AlterField(
            model_name='location',
            name='end_data',
            field=models.DateField(blank=True, verbose_name='Дата окончания рассадки'),
        ),
    ]
