# Generated by Django 4.0.1 on 2022-03-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_rename_save_location_save_bd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='end_data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания рассадки'),
        ),
    ]
